# -*- coding: utf-8 -*-
"""Salinan dari volume tabung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1791NJjhoedsIx65ifQsCDynnf1OIayQ0
"""

import streamlit as st
import math

# --- Fungsi untuk Menghitung Volume Tabung ---
def hitung_volume_tabung(jari_jari, tinggi):
    """
    Menghitung luas alas dan volume tabung berdasarkan jari-jari dan tinggi.
    Mengembalikan tuple (luas_alas, volume).
    """
    luas_alas = math.pi * (jari_jari ** 2)
    volume = luas_alas * tinggi
    return luas_alas, volume

# --- Konfigurasi Halaman Streamlit ---
# Mengatur judul tab browser, ikon, layout, dan status sidebar awal
st.set_page_config(
    page_title="Kalkulator Volume Tabung",
    page_icon=":test_tube:", # Menggunakan emoji sebagai ikon
    layout="centered",
    initial_sidebar_state="expanded"
)

# --- Judul Utama Aplikasi ---
st.title("🧮 Kalkulator Volume Tabung Interaktif")
st.markdown("---") # Garis pemisah visual
st.write("""
Aplikasi ini dirancang untuk membantu Anda menghitung **volume tabung** dengan mudah dan menampilkan
langkah-langkah perhitungannya secara jelas. Masukkan nilai **jari-jari** dan **tinggi** tabung,
lalu lihat hasilnya!
""")

# --- Input Pengguna ---
st.header("Masukkan Dimensi Tabung")

# Menggunakan kolom untuk tata letak input yang lebih rapi
col1, col2 = st.columns(2)

with col1:
    # Input untuk jari-jari dengan nilai default dan rentang
    jari_jari = st.number_input(
        "**Jari-jari (r)**",
        min_value=0.0,
        value=5.0, # Nilai awal
        step=0.1,  # Langkah perubahan nilai
        help="Jarak dari pusat alas lingkaran ke tepi alas tabung."
    )

with col2:
    # Input untuk tinggi dengan nilai default dan rentang
    tinggi = st.number_input(
        "**Tinggi (t)**",
        min_value=0.0,
        value=10.0, # Nilai awal
        step=0.1,  # Langkah perubahan nilai
        help="Jarak vertikal dari alas ke tutup tabung."
    )

st.markdown("---")

# --- Tombol untuk Memicu Perhitungan ---
if st.button("🚀 Hitung Volume!"):
    # Validasi input: jari-jari dan tinggi tidak boleh nol atau negatif
    if jari_jari <= 0 or tinggi <= 0:
        st.error("⚠️ **Jari-jari** dan **tinggi** harus lebih besar dari nol. Mohon periksa input Anda.")
    else:
        # Panggil fungsi perhitungan
        luas_alas, volume = hitung_volume_tabung(jari_jari, tinggi)

        st.success("✨ **Perhitungan Berhasil!**")

        # --- Bagian Detail Perhitungan (Discovery Learning) ---
        st.subheader("📊 Detail Perhitungan:")

        # Menampilkan perhitungan luas alas
        st.info(f"**Langkah 1: Hitung Luas Alas (Lingkaran)**")
        st.code(f"Rumus Luas Alas = π * r²")
        st.markdown(f"""
            Luas Alas = `{math.pi:.4f}` (π) × `{jari_jari}`²
            <br>
            Luas Alas = `{math.pi:.4f}` × `{jari_jari * jari_jari}`
            <br>
            **Luas Alas = `{luas_alas:.2f}`**
            """, unsafe_allow_html=True)

        # Menampilkan perhitungan volume
        st.info(f"**Langkah 2: Hitung Volume Tabung**")
        st.code(f"Rumus Volume = Luas Alas × Tinggi")
        st.markdown(f"""
            Volume = `{luas_alas:.2f}` (Luas Alas) × `{tinggi}` (Tinggi)
            <br>
            **Volume = `{volume:.2f}`**
            """, unsafe_allow_html=True)

        # Efek visual balon
        st.balloons()

        # --- Kesimpulan Hasil (dengan HTML & CSS untuk tampilan menarik) ---
        st.markdown(f"""
        <div style="background-color:#e0ffe0; padding: 20px; border-radius: 12px; border: 2px solid #66bb6a; box-shadow: 3px 3px 8px rgba(0,0,0,0.2);">
            <h3 style="color:#2e7d32; text-align: center; margin-bottom: 15px;">✅ Kesimpulan Hasil Perhitungan</h3>
            <p style="font-size:18px; text-align: center;">
                Untuk tabung dengan **jari-jari** <b style="color:#007bff;">{jari_jari}</b>
                dan **tinggi** <b style="color:#007bff;">{tinggi}</b>,
                volume yang didapatkan adalah:
            </p>
            <h1 style="color:#c62828; font-size:48px; text-align: center; margin-top: 10px; margin-bottom: 5px;">{volume:.2f}</h1>
            <p style="font-size:14px; color:#555; text-align: center;">
                <i>*Pastikan satuan volume sesuai dengan satuan input Anda (misal cm³ jika menggunakan cm).*</i>
            </p>
        </div>
        """, unsafe_allow_html=True)

# --- Sidebar untuk Informasi Tambahan ---
st.sidebar.title("ℹ️ Tentang Aplikasi Ini")
st.sidebar.info(
    "Aplikasi ini adalah kalkulator volume tabung interaktif yang dibangun menggunakan Streamlit. "
    "Dirancang untuk kemudahan penggunaan dan pemahaman konsep di balik perhitungan volume."
)
st.sidebar.markdown("---")
st.sidebar.text("© 2025 Python Programmer")
st.sidebar.caption("Dibuat dengan ❤️ untuk pembelajaran interaktif.")